import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { getProjects } from "../services/projectService";
import type { Project } from "../services/projectService";

const statusColor = (status: string) => status.toLowerCase() === "completed" ? { background: "#dcfce7", color: "#166534" } : status.toLowerCase() === "planning" ? { background: "#fef3c7", color: "#92400e" } : { background: "#dbeafe", color: "#1d4ed8" };

export default function DashboardPage() {
  const navigate = useNavigate(); const [projects, setProjects] = useState<Project[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { try { setLoading(true); setError(""); setProjects(await getProjects()); } catch { setError("Unable to load projects. Please check that the backend is running."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const stats = useMemo(() => [{ label: "Total Projects", value: projects.length, icon: "▦" }, { label: "Team Members", value: projects.reduce((sum, project) => sum + project.members.length, 0), icon: "♟" }, { label: "In Progress", value: projects.filter((project) => project.status.toLowerCase() === "in progress").length, icon: "◷" }, { label: "Completed", value: projects.filter((project) => project.status.toLowerCase() === "completed").length, icon: "✓" }], [projects]);
  return <div style={{ minHeight: "100vh", background: "#f8fafc", color: "#0f172a", fontFamily: "Inter, Arial, sans-serif" }}>
    <header style={{ height: 64, background: "#fff", borderBottom: "1px solid #e2e8f0", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 48px" }}><button onClick={() => navigate("/dashboard")} style={{ display: "flex", alignItems: "center", gap: 10, border: 0, background: "none", cursor: "pointer" }}><span style={{ width: 34, height: 34, display: "grid", placeItems: "center", borderRadius: 8, background: "#dbeafe", color: "#2563eb", fontWeight: 900 }}>✓</span><b style={{ fontSize: 20 }}>CollabBoard</b></button><nav style={{ display: "flex", gap: 26 }}><button onClick={() => navigate("/dashboard")} style={{ border: 0, background: "none", fontWeight: 700, cursor: "pointer" }}>Dashboard</button><button onClick={() => navigate("/projects")} style={{ border: 0, background: "none", color: "#475569", cursor: "pointer" }}>All Projects</button><button onClick={() => navigate("/create-project")} style={{ border: 0, background: "none", color: "#475569", cursor: "pointer" }}>Create Project</button></nav><button onClick={() => navigate("/profile")} style={{ border: 0, borderRadius: "50%", width: 34, height: 34, background: "#0f172a", color: "#fff", cursor: "pointer" }}>●</button></header>
    <main style={{ maxWidth: 1240, margin: "0 auto", padding: "32px 48px" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 24 }}><div><h1 style={{ margin: 0, fontSize: 28 }}>Welcome to your <span style={{ color: "#2563eb" }}>Dashboard</span></h1><p style={{ margin: "7px 0 0", color: "#64748b" }}>Track projects and team members in one place.</p></div><button onClick={() => void load()} disabled={loading} style={{ border: "1px solid #bfdbfe", background: "#eff6ff", color: "#1d4ed8", padding: "10px 14px", borderRadius: 8, fontWeight: 700, cursor: "pointer" }}>{loading ? "Refreshing..." : "↻ Refresh"}</button></div>{error && <div style={{ color: "#991b1b", background: "#fee2e2", padding: 14, borderRadius: 8, marginBottom: 20 }}>{error}</div>}
      <section style={{ display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 16, marginBottom: 24 }}>{stats.map((stat) => <div key={stat.label} style={{ background: "#fff", border: "1px solid #e2e8f0", borderRadius: 12, padding: 18, display: "flex", alignItems: "center", gap: 14 }}><span style={{ width: 38, height: 38, display: "grid", placeItems: "center", borderRadius: 8, background: "#eff6ff", color: "#2563eb", fontSize: 19 }}>{stat.icon}</span><div><div style={{ color: "#64748b", fontSize: 13, fontWeight: 600 }}>{stat.label}</div><div style={{ fontSize: 24, fontWeight: 800 }}>{loading ? "–" : stat.value}</div></div></div>)}</section>
      <section style={{ background: "#fff", border: "1px solid #e2e8f0", borderRadius: 12, overflow: "hidden" }}><div style={{ padding: 20, display: "flex", justifyContent: "space-between", alignItems: "center" }}><div><h2 style={{ margin: 0, fontSize: 18 }}>Projects overview</h2><p style={{ color: "#64748b", fontSize: 13, margin: "5px 0 0" }}>Live data from the project backend.</p></div><button onClick={() => navigate("/projects")} style={{ border: 0, background: "none", color: "#2563eb", fontWeight: 700, cursor: "pointer" }}>View all projects</button></div>{loading ? <p style={{ padding: 20, color: "#64748b" }}>Loading projects...</p> : projects.length === 0 ? <p style={{ padding: 20, color: "#64748b" }}>No projects available.</p> : <table style={{ width: "100%", borderCollapse: "collapse", textAlign: "left" }}><thead><tr style={{ background: "#eff6ff", color: "#1e3a8a", fontSize: 13 }}><th style={{ padding: "12px 20px" }}>PROJECT</th><th style={{ padding: "12px 20px" }}>STATUS</th><th style={{ padding: "12px 20px" }}>MEMBERS</th><th style={{ padding: "12px 20px", textAlign: "right" }}>ACTION</th></tr></thead><tbody>{projects.map((project) => <tr key={project.id} style={{ borderTop: "1px solid #f1f5f9" }}><td style={{ padding: "16px 20px" }}><b>{project.name}</b><div style={{ color: "#64748b", fontSize: 13, marginTop: 4 }}>{project.description}</div></td><td style={{ padding: "16px 20px" }}><span style={{ ...statusColor(project.status), padding: "5px 9px", borderRadius: 999, fontSize: 12, fontWeight: 700 }}>{project.status}</span></td><td style={{ padding: "16px 20px", color: "#475569", fontSize: 14 }}>{project.members.map((member) => member.name).join(", ") || "No members assigned"}</td><td style={{ padding: "16px 20px", textAlign: "right" }}><button onClick={() => navigate(`/project-members?id=${project.id}`)} style={{ border: "1px solid #bfdbfe", background: "#dbeafe", color: "#1d4ed8", padding: "7px 11px", borderRadius: 7, fontWeight: 700, cursor: "pointer" }}>View members</button></td></tr>)}</tbody></table>}</section></main></div>;
}
