import { useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { getProjectById, updateProject } from "../services/projectService";
import type { Project, ProjectMember } from "../services/projectService";

export default function ViewProjectMembersPage() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const id = params.get("id");
  const [project, setProject] = useState<Project | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!id) { setError("Select a project from the dashboard first."); setLoading(false); return; } getProjectById(id).then(setProject).catch(() => setError("Unable to load project members.")).finally(() => setLoading(false)); }, [id]);
  const addMember = async () => { if (!project) return; const name = window.prompt("Member name:")?.trim(); if (!name) return; const email = window.prompt("Member email:")?.trim() ?? ""; const role = window.prompt("Member role:", "Member")?.trim() || "Member"; const member: ProjectMember = { name, email, role }; try { setSaving(true); setError(""); setProject(await updateProject(project.id, { members: [...project.members, member] })); } catch { setError("Unable to add the member. Please try again."); } finally { setSaving(false); } };
  return <div style={{ minHeight: "100vh", background: "#f8fafc", color: "#0f172a", fontFamily: "Inter, Arial, sans-serif" }}>
    <header style={{ height: 64, background: "#fff", borderBottom: "1px solid #e2e8f0", display: "flex", alignItems: "center", padding: "0 48px" }}><button onClick={() => navigate("/dashboard")} style={{ display: "flex", alignItems: "center", gap: 10, border: 0, background: "none", cursor: "pointer" }}><span style={{ width: 34, height: 34, display: "grid", placeItems: "center", borderRadius: 8, background: "#dbeafe", color: "#2563eb", fontWeight: 900 }}>✓</span><b style={{ fontSize: 20 }}>CollabBoard</b></button></header>
    <main style={{ maxWidth: 1120, margin: "0 auto", padding: "32px 48px" }}><button onClick={() => navigate("/dashboard")} style={{ border: 0, background: "none", color: "#475569", fontWeight: 600, cursor: "pointer", padding: 0 }}>← Back to Dashboard</button><div style={{ display: "flex", justifyContent: "space-between", alignItems: "end", margin: "24px 0" }}><div><h1 style={{ margin: 0, fontSize: 28 }}>{project?.name ?? "Project Members"}</h1><p style={{ margin: "7px 0 0", color: "#64748b" }}>Manage and view members assigned to this project.</p></div><div style={{ display: "flex", alignItems: "center", gap: 12 }}>{project && <span style={{ background: "#eff6ff", color: "#1d4ed8", padding: "7px 10px", borderRadius: 999, fontWeight: 700, fontSize: 13 }}>{project.members.length} member{project.members.length === 1 ? "" : "s"}</span>}<button onClick={() => void addMember()} disabled={!project || saving} style={{ border: 0, background: "#2563eb", color: "#fff", borderRadius: 8, padding: "10px 14px", fontWeight: 700, cursor: "pointer" }}>{saving ? "Saving..." : "+ Add Member"}</button></div></div>
      {error ? <div role="alert" style={{ background: "#fee2e2", color: "#991b1b", padding: 14, borderRadius: 8 }}>{error}</div> : loading ? <div style={{ background: "#fff", padding: 24, borderRadius: 12, color: "#64748b" }}>Loading members...</div> : <section style={{ background: "#fff", border: "1px solid #e2e8f0", borderRadius: 12, overflow: "hidden" }}><table style={{ width: "100%", borderCollapse: "collapse", textAlign: "left" }}><thead><tr style={{ background: "#2563eb", color: "#fff", fontSize: 13 }}><th style={{ padding: "14px 20px" }}>MEMBER</th><th style={{ padding: "14px 20px" }}>ROLE</th><th style={{ padding: "14px 20px" }}>EMAIL</th></tr></thead><tbody>{project?.members.length ? project.members.map((member, index) => <tr key={`${member.email}-${index}`} style={{ borderBottom: index < project.members.length - 1 ? "1px solid #f1f5f9" : undefined }}><td style={{ padding: "17px 20px", fontWeight: 700 }}>{member.name}</td><td style={{ padding: "17px 20px" }}><span style={{ background: "#f1f5f9", color: "#334155", borderRadius: 999, padding: "5px 9px", fontSize: 12, fontWeight: 700 }}>{member.role || "Member"}</span></td><td style={{ padding: "17px 20px", color: member.email ? "#334155" : "#94a3b8" }}>{member.email || "Email not added"}</td></tr>) : <tr><td colSpan={3} style={{ padding: 28, textAlign: "center", color: "#64748b" }}>No members have been assigned to this project.</td></tr>}</tbody></table></section>}</main>
  </div>;
}
